export const geminiLinks = [
  {
    id: 'gem-01',
    url: 'https://share.gemini.google/rFYOdcgIdYLO',
    author: '二シャー♥️',
    authorName: 'ณิชา ขำสุนทร',
    role: 'Customer Service Supervisor',
    department: 'Customer Experience (CXTSP)',
    title: 'Gemini Session: แนวทางวิเคราะห์และยกระดับความพึงพอใจคนไข้ OPD',
    description: 'บันทึกบทสนทนาและชุดคำสั่ง AI ในการวิเคราะห์เคสบริการผู้ป่วยนอก และสร้างข้อเสนอแนะเชิงรุก',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Customer Experience', 'OPD Service', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 10:16',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-02',
    url: 'https://share.gemini.google/aiRYbMlRk1ek',
    author: 'Beer~Бир💕🐱🌷',
    authorName: 'วรจันทร์ สุตันตานนท์',
    role: 'Patient & Relative Apartment Manager',
    department: 'Ancillary Support Services (ASD)',
    title: 'Gemini Session: การจัดการห้องพักผู้ป่วยและระบบสื่อสารสองภาษา',
    description: 'โครงสร้างคำสั่ง AI สำหรับแปลภาษา จัดทำประกาศแจ้งเตือน และจัดการข้อร้องเรียนในหอพักผู้ป่วย',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Residence Operations', 'Bilingual Notice', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 10:16',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-03',
    url: 'https://share.gemini.google/vuy8QNajXo7k',
    author: 'Ampp',
    authorName: 'อัมพิกา บุญมี',
    role: 'CX & Partner Coordination Officer',
    department: 'Customer Experience (CXTSP)',
    title: 'Gemini Session: แผนงานประสานคู่สัญญาและยกระดับ Journey ผู้รับบริการ',
    description: 'การนำ AI มาช่วยวางแผนและจัดทำ Workflow สัมพันธ์ลูกค้าและคู่สัญญาโรงพยาบาล',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Partner Relations', 'Journey Design', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 10:16',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-04',
    url: 'https://share.gemini.google/TxvThBjBifWo',
    author: 'BaiFern',
    authorName: 'ใบเฟิร์น พัชรพร',
    role: 'Insurance Case Coordinator',
    department: 'Customer Experience (CXTSP)',
    title: 'Gemini Session: ระบบตรวจสอบสิทธิประกันสุขภาพและการประเมินความคุ้มครอง',
    description: 'บทสนทนาการวางกรอบ Prompt เพื่อตรวจเช็คความคุ้มครองและลดข้อผิดพลาดในขั้นตอนประสานงานประกัน',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Insurance Ops', 'Pre-Authorization', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 10:16',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-05',
    url: 'https://share.gemini.google/FBzCOxeH0R7u',
    author: 'MAI❄️',
    authorName: 'ไหม รัตนาภรณ์',
    role: 'Patient Experience Specialist',
    department: 'Customer Experience (CXTSP)',
    title: 'Gemini Session: มาตรการเยียวยาข้อร้องเรียนและการบริการที่เกินความคาดหมาย',
    description: 'การสร้าง Prompt Template สำหรับ Service Recovery และการร่างคำชี้แจงทางการแพทย์อย่างสุภาพ',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Service Recovery', 'Empathetic Response', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 10:16',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-06',
    url: 'https://share.gemini.google/KkFgfGN8VCeI',
    author: 'llu:LLuว',
    authorName: 'คุณแอล',
    role: 'Logistics & Transport Coordinator',
    department: 'Ancillary Support Services (ASD)',
    title: 'Gemini Session: การบริหารจัดการคิวยานพาหนะและรถพยาบาลฉุกเฉิน',
    description: 'แนวทางคำสั่ง AI จัดการตารางเดินรถ การคำนวณระยะเวลา และลดรอบการรอคอยของคนไข้',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Ambulance & Transport', 'Queue Optimization', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 10:17',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-07',
    url: 'https://gemini.google.com/share/d2792ce9dc7f?skid=aaa07dc1-286d-4633-93b4-faddee8e19d3',
    author: 'Honghern (( fah ))',
    authorName: 'หงษ์ฟ้า สายแวว',
    role: 'Assistant ASD Manager',
    department: 'Ancillary Support Services (ASD)',
    title: 'Gemini Session: การจัดตารางเวรและเบิกจ่ายงบประมาณสนับสนุนฝ่าย',
    description: 'คำสั่ง AI ช่วยคำนวณเบิกจ่ายรถตู้รายวัน จัดตารางกะบุคลากร และสรุป KPI ส่งต่อผู้บริหาร',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Staff Rostering', 'Budget Audit', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 10:17',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-08',
    url: 'https://gemini.google.com/share/57d111c2de03?skid=c9aedc75-e9cc-44e4-b9fd-cbad4fb6080b',
    author: 'BeE_SEA💝💖',
    authorName: 'คุณบี (ตัวแทนพี่บูน)',
    role: 'Nursing & Ancillary Supervisor',
    department: 'Ancillary Support Services (ASD)',
    title: 'Gemini Session: แผนงานระบบสนับสนุนพยาบาลและการเคลื่อนย้ายผู้ป่วย (เวรเปล)',
    description: 'วิเคราะห์ขั้นตอนเวรเปลและลดขวดคอในการเคลื่อนย้ายผู้ป่วยในห้องฉุกเฉินและหอพักผู้ป่วย',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Patient Transfer', 'Nursing Support', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 10:18',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-09',
    url: 'https://gemini.google.com/share/91679afb1e26?skid=35a440a9-4e3d-4a3f-8214-d8cac8dc8e7a',
    author: 'BeE_SEA💝💖',
    authorName: 'คุณบี (ตัวแทนพี่นุ๊ก)',
    role: 'Food & Nutrition Services Lead',
    department: 'Ancillary Support Services (ASD)',
    title: 'Gemini Session: ระบบจัดการอาหารทางการแพทย์และบริการโภชนาการผู้ป่วย',
    description: 'การใช้ AI วางแผนเมนูอาหารควบคุมโรคและจัดทำแบบสำรวจความพึงพอใจด้านโภชนาการ',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Clinical Nutrition', 'Catering Strategy', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 10:18',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-10',
    url: 'https://share.gemini.google/YsBQehxj2tBQ',
    author: 'BeE_SEA💝💖',
    authorName: 'คุณบี (ตัวแทนน้องปู)',
    role: 'Facilities & Support Services',
    department: 'Facilities Management',
    title: 'Gemini Session: การบริหารจัดการงานซ่อมบำรุงและตรวจประเมินคู่สัญญา',
    description: 'การร่างเกณฑ์ประเมินคู่สัญญาเครื่องกรองน้ำ การกำจัดแมลง และการติดตามความคืบหน้ารายงานแจ้งซ่อม',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Facility Maintenance', 'Vendor SLA', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 10:18',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-11',
    url: 'https://docs.google.com/document/d/1HIfkx8rgKghvlI-k-wA9b9cy10zBcYp32enxXCaY6iw/edit?tab=t.0',
    author: 'JakjaN',
    authorName: 'จนิษฐ์ฌาภา มากอยู่',
    role: 'Insurance Case Coordinator',
    department: 'Customer Experience (CXTSP)',
    title: 'Google Docs: สรุปแนวทางการประสานสิทธิประโยชน์และตัวแทนประกันชีวิต',
    description: 'เอกสารสรุปขั้นตอนวิเคราะห์การเบิกจ่ายประกัน ปัญหาคอขวด และแนวทางแก้ไขด้วย AI',
    type: 'google_docs',
    typeLabel: 'Google Docs Strategy',
    tags: ['Insurance Strategy', 'Collaborative Doc', 'JCI v8'],
    date: '14 ก.ย. 2569 10:20',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-12',
    url: 'https://docs.google.com/document/d/1SAuJL6ZhhI11uONz_wgi-z9qBF1SCGXU1LkGp1Imz3Y/edit?usp=sharing',
    author: '二シャー♥️',
    authorName: 'ณิชา ขำสุนทร',
    role: 'Customer Service Supervisor',
    department: 'Customer Experience (CXTSP)',
    title: 'Google Docs: แผนปฏิบัติการยกระดับบริการส่วนหน้าและการบริหารข้อร้องเรียน',
    description: 'เอกสารยุทธศาสตร์ของหน่วยบริการลูกค้า ในการนำระบบ AI ช่วยคัดกรองปัญหาและตอบสนองทันท่วงที',
    type: 'google_docs',
    typeLabel: 'Google Docs Strategy',
    tags: ['Frontline Service', 'Complaint Handling', 'Action Plan'],
    date: '14 ก.ย. 2569 10:21',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-13',
    url: 'https://docs.google.com/document/d/1E_8o0P_cRhZjXdxg70U8p-MjYiin0X6qW2BJBfFbJCY/edit?usp=sharing',
    author: 'Boss',
    authorName: 'ผู้บริหารระดับสูง (Executive Leadership)',
    role: 'Chief Operations & Strategy Advisor',
    department: 'Executive Leadership',
    title: 'Google Docs: แผนยุทธศาสตร์ AI Transformation โรงพยาบาลเวชธานี 2026',
    description: 'วิสัยทัศน์ผู้บริหาร ทิศทางการลงทุน AI และการเชื่อมโยงระบบ PACC, ASD และ CXTSP สู่เป้าหมายองค์กร',
    type: 'google_docs',
    typeLabel: 'Google Docs Strategy',
    tags: ['Executive Vision', 'Transformation Roadmap', 'High Priority'],
    date: '14 ก.ย. 2569 10:24',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-14',
    url: 'https://docs.google.com/document/d/1Gkxl-LHowo6YmmbLZHJ4K2IyaSj-l2WEkp5O0yfsxjA/edit?usp=sharing',
    author: 'Beer~Бир💕🐱🌷',
    authorName: 'วรจันทร์ สุตันตานนท์',
    role: 'Patient & Relative Apartment Manager',
    department: 'Ancillary Support Services (ASD)',
    title: 'Google Docs: คู่มือมาตรฐานการปฏิบัติงานที่พักผู้ป่วยและญาติ (Vejthani Residence SOP)',
    description: 'ระเบียบปฏิบัติและแนวทางพัฒนาการจองห้องพัก การเช็คอิน-เอาท์ และมาตรการความปลอดภัย',
    type: 'google_docs',
    typeLabel: 'Google Docs Strategy',
    tags: ['Residence SOP', 'Standard Procedures', 'Hospitality'],
    date: '14 ก.ย. 2569 10:25',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-15',
    url: 'https://share.gemini.google/uxV843veXFwA',
    author: 'Aun(อุ๊นอุ่น)',
    authorName: 'อรุณี อภิวัฒนานันท์',
    role: 'Quality Assurance Officer',
    department: 'Customer Experience (CXTSP)',
    title: 'Gemini Session: การตรวจประเมินคุณภาพและมาตรฐานความปลอดภัย JCI v8',
    description: 'ชุดคำสั่งตรวจสอบการปฏิบัติตามเกณฑ์ JCI และการวิเคราะห์ข้อกำหนดสิทธิผู้ป่วยด้วย Gemini',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['JCI v8 Audit', 'Quality Assurance', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 10:25',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-16',
    url: 'https://docs.google.com/document/d/1tLzSXvtDdznCpYfK2f5ZRRUx6CVI46L8wZIvrcmZDqs/edit?usp=sharing',
    author: 'Aun(อุ๊นอุ่น)',
    authorName: 'อรุณี อภิวัฒนานันท์',
    role: 'Quality Assurance Officer',
    department: 'Customer Experience (CXTSP)',
    title: 'Google Docs: รายงานสรุปมาตรการควบคุมความปลอดภัยและธรรมาภิบาลข้อมูล AI',
    description: 'เอกสารนโยบายความรับผิดชอบและการปกป้องข้อมูลคนไข้ตาม พ.ร.บ. คุ้มครองข้อมูลส่วนบุคคล (PDPA)',
    type: 'google_docs',
    typeLabel: 'Google Docs Strategy',
    tags: ['PDPA Governance', 'Compliance Report', 'Data Security'],
    date: '14 ก.ย. 2569 10:25',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-17',
    url: 'https://share.gemini.google/4KBWhnK2QbVC',
    author: 'Boss',
    authorName: 'ผู้บริหารระดับสูง (Executive Leadership)',
    role: 'Chief Operations & Strategy Advisor',
    department: 'Executive Leadership',
    title: 'Gemini Session: วิเคราะห์การคืนทุน (ROI) และดัชนีชี้วัดความคุ้มค่าโครงการ AI',
    description: 'การใช้ Gemini คำนวณต้นทุนการไม่ลงมือทำ (Cost of Inaction) เทียบกับงบประมาณลงทุน AI ระบบโรงพยาบาล',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['ROI & Cost of Inaction', 'Financial Model', 'Executive Brief'],
    date: '14 ก.ย. 2569 10:27',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-18',
    url: 'https://gemini.google.com/share/5b8e2d47123e?skid=82b11fbc-fb86-485c-8bab-34b93f38de9a',
    author: 'Honghern (( fah ))',
    authorName: 'หงษ์ฟ้า สายแวว',
    role: 'Assistant ASD Manager',
    department: 'Ancillary Support Services (ASD)',
    title: 'Gemini Session: รายงานวิเคราะห์ประสิทธิภาพการใช้น้ำมันและการซ่อมบำรุงยานพาหนะ',
    description: 'การสกัดสถิติการใช้งานรถตู้โรงพยาบาลและสร้างรายงานสรุปเชิงยุทธศาสตร์เพื่อลดค่าใช้จ่ายพลังงาน',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Energy Efficiency', 'Fleet Management', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 12:15',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-19',
    url: 'https://gemini.google.com/share/56736263e1d4?skid=fe3423e2-39a9-409d-a7f2-aa0cb1d4465c',
    author: 'BeE_SEA💝💖',
    authorName: 'คุณบี (ตัวแทนพี่บูน)',
    role: 'Nursing & Ancillary Supervisor',
    department: 'Ancillary Support Services (ASD)',
    title: 'Gemini Session: โครงสร้างคำสั่งประเมินภาระงานพยาบาลและการส่งต่อเวชระเบียน',
    description: 'การออกแบบ Prompt เพื่อช่วยวิเคราะห์เวลาทำงานและสร้างระบบรองรับการส่งเวรพยาบาลให้ราบรื่น',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Nursing Workload', 'Shift Handover', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 12:18',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-20',
    url: 'https://gemini.google.com/share/00985ffd478b?skid=39bd0d10-9765-4440-884a-8fada398bf07',
    author: 'BeE_SEA💝💖',
    authorName: 'คุณบี (ตัวแทนกลุ่ม Ancillary)',
    role: 'Operations Coordinator',
    department: 'Ancillary Support Services (ASD)',
    title: 'Gemini Session: การรวบรวมตัวชี้วัด Cross-Functional ระหว่างฝ่าย PACC และ ASD',
    description: 'ชุดคำสั่งสังเคราะห์ข้อมูลการส่งต่อคนไข้ระหว่างจุดรับรองลูกค้าและหน่วยงานสนับสนุน',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Cross-Department', 'Inter-unit SLA', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 12:18',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-21',
    url: 'https://gemini.google.com/share/29718be8c09d?skid=c633ca47-aa17-473e-9ea5-ef6b7d3c7bb2',
    author: 'BeE_SEA💝💖',
    authorName: 'คุณบี (ตัวแทนพี่ใหม่)',
    role: 'Patient Experience Specialist',
    department: 'Customer Experience (CXTSP)',
    title: 'Gemini Session: การวิเคราะห์ Patient Journey แบบเรียลไทม์ผ่าน Touchpoint ดิจิทัล',
    description: 'โครงสร้างแบบทดสอบการประเมินความพึงพอใจคนไข้ชาวต่างชาติและการตอบรับข้อเสนอแนะทันที',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['International Patients', 'Digital Touchpoint', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 11:50',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-22',
    url: 'https://gemini.google.com/gem/1udPY7rfBLsfL9LCBjq4QAO1_B6LTJfYG?usp=sharing',
    author: 'Poo ~☀️',
    authorName: 'พรพิรุณ วงษ์วรางกูร',
    role: 'Facilities & Support Services Manager',
    department: 'Facilities Management',
    title: 'Custom Gem: ผู้ช่วยบริหารงานแม่บ้านและจัดการห้องพักผู้ป่วย (Housekeeping Gem)',
    description: 'Google Gem เฉพาะทาง ออกแบบมาเพื่อตรวจนับผ้า ควบคุมขยะติดเชื้อ ออกใบ PR และประเมินมาตรฐานห้องพร้อมรับ',
    type: 'custom_gem',
    typeLabel: 'Google Custom Gem Agent',
    tags: ['Housekeeping Agent', 'Infection Control', 'Custom Gem'],
    date: '14 ก.ย. 2569 11:54',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-23',
    url: 'https://gemini.google.com/gem/1G8n0kfI0gEb8Cl4hwUYr6ANx1ZBuqUAJ?usp=sharing',
    author: 'llu:LLuว',
    authorName: 'คุณแอล',
    role: 'Logistics & Transport Coordinator',
    department: 'Ancillary Support Services (ASD)',
    title: 'Custom Gem: ระบบอัจฉริยะจัดสรรยานพาหนะและควบคุมเส้นทาง (Fleet Dispatch Gem)',
    description: 'Google Gem อัตโนมัติในการจัดรอบการเดินทาง คำนวณเบิกจ่าย และประสานงานส่งต่อผู้ป่วยด่วน',
    type: 'custom_gem',
    typeLabel: 'Google Custom Gem Agent',
    tags: ['Fleet Dispatch', 'Logistics Intelligence', 'Custom Gem'],
    date: '14 ก.ย. 2569 11:55',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  },
  {
    id: 'gem-24',
    url: 'https://share.gemini.google/9ljhFuX9Wtfd',
    author: 'llu:LLuว',
    authorName: 'คุณแอล',
    role: 'Logistics & Transport Coordinator',
    department: 'Ancillary Support Services (ASD)',
    title: 'Gemini Session: การทวนสอบความปลอดภัยในการขับขี่และการซ่อมบำรุงตามรอบระยะ',
    description: 'แบบฟอร์มคำสั่ง AI ตรวจเช็คสภาพยานพาหนะก่อนออกปฏิบัติหน้าที่และการบันทึกประวัติการบำรุงรักษา',
    type: 'gemini_share',
    typeLabel: 'Gemini Shared Chat',
    tags: ['Vehicle Safety', 'Preventive Maintenance', 'Gemini 1.5'],
    date: '14 ก.ย. 2569 12:14',
    source: '[LINE]AI for PACC+ASD+CXTSP 2026.txt'
  }
];